remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Mechaneus Security Research and Bug Hunting
description: Welcome to the my Security Research page. I am a passionate bug hunter and security researcher, dedicated to discovering vulnerabilities and contributing to a safer digital world.
